version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  install:
    commands:
      - export DOCKER_HOST=tcp://$AWS_DOCKER_HOST:2375
      - docker ps
      # Authenticate the remote node in AWS ECR
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      # To update a running service in a Swarm node:
      # - docker service update --image $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG $SERVICE_NAME
      # To update a running service from a Compose:
      - docker-compose -p $COMPOSE_PROJECT_NAME up -d --no-deps --build $SERVICE_NAME
